//firebase_options.dart
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGQHEiFZKo5Mb4qihXrbws-wx77w-kfh8',
    appId: '1:692047291199:web:1745c07172fe5e3e0fa98a',
    messagingSenderId: '692047291199',
    projectId: 'imposing-bee-421110',
    authDomain: 'imposing-bee-421110.firebaseapp.com',
    databaseURL: 'https://imposing-bee-421110-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'imposing-bee-421110.appspot.com',
    measurementId: 'G-ZFQ2Q4ZGFF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBe3LRyi3Q0F191tdYZk6cIqpMrN6AnDNo',
    appId: '1:692047291199:android:b7cd5b5f0eaf78d40fa98a',
    messagingSenderId: '692047291199',
    projectId: 'imposing-bee-421110',
    databaseURL: 'https://imposing-bee-421110-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'imposing-bee-421110.appspot.com',
  );

}