name: polyglotpath
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  animated_splash_screen: ^1.3.0
  google_sign_in: ^6.2.1
  google_sign_in_web: ^0.12.4
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.2.3
  image_picker: ^1.1.1
  permission_handler: ^11.3.1
  cloud_firestore: ^5.0.1
  firebase_storage: ^12.0.1
  provider: ^6.1.2
  share: ^2.0.4
  google_fonts: ^6.2.1
  intl: ^0.19.0
  timeago: ^3.6.1
  geolocator: ^12.0.0
  geocoding: ^3.0.0
  url_launcher: ^6.3.0
  cached_network_image: ^3.3.1
  share_plus: ^9.0.0
  photo_view: ^0.15.0
  google_generative_ai: ^0.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/polyglotpath.jpeg
    - assets/google.png
    - assets/korea.png
    - assets/japan.png
    - assets/english.png
    - assets/russia.png
    - assets/default_profile_image.png
    - assets/gemini_ai_avatar.png